-- 작업 데이터베이스 변경
USE employees;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM DEPT_EMP;
SELECT * FROM TITLES;
SELECT * FROM SALARIES;
SELECT * FROM DEPT_MANAGER;

-- 1. 1990년도에 입사한 직원 조회
SELECT * 
FROM EMPLOYEES E
WHERE E.HIRE_DATE BETWEEN '1990-01-01' AND '1990-12-31'
ORDER BY E.HIRE_DATE DESC;

-- 2. 이름에 K가 포함된 직원 조회
SELECT E.EMP_NO, CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) NAME, E.HIRE_DATE
FROM EMPLOYEES E
-- WHERE E.FIRST_NAME LIKE '%K%' OR E.FIRST_NAME LIKE '%k%' OR ...
-- WHERE LOWER(E.FIRST_NAME) LIKE '%k%' OR LOWER(E.LAST_NAME) LIKE '%k%'
WHERE LOWER(CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)) LIKE '%k%';

-- 3. 성별 직원수 조회
SELECT E.GENDER, COUNT(E.GENDER) 직원수
FROM EMPLOYEES E
GROUP BY E.GENDER;

-- 4. 사원 정보 조회 (employees 테이블의 모든 정보, 현재 부서이름, 현재 직급)
SELECT E.*, D.DEPT_NAME, T.TITLE
FROM EMPLOYEES E, DEPARTMENTS D, DEPT_EMP DE, TITLES T
WHERE E.EMP_NO = DE.EMP_NO AND D.DEPT_NO = DE.DEPT_NO AND E.EMP_NO = T.EMP_NO
	  AND
      T.TO_DATE = '9999-01-01' AND DE.TO_DATE = '9999-01-01'
ORDER BY E.EMP_NO;

-- 5. 현재 개발부서(Development)에 근무하는 직원 정보 조회
SELECT E.*
FROM EMPLOYEES E, DEPARTMENTS D, DEPT_EMP DE
WHERE E.EMP_NO = DE.EMP_NO AND D.DEPT_NO = DE.DEPT_NO
	  AND DE.TO_DATE = '9999-01-01'
      AND D.DEPT_NAME = 'Development';
      
-- 6. 현재 급여가 50000 ~ 60000인 직원 조회
SELECT E.*, S.SALARY
FROM EMPLOYEES E, SALARIES S
WHERE E.EMP_NO = S.EMP_NO AND 
	  S.TO_DATE = '9999-01-01' AND
      -- S.SALARY BETWEEN 50000 AND 60000;
      S.SALARY >= 50000 AND S.SALARY < 60000;
      
-- 7. 부서별 직원의 평균 급여 조회 
SELECT DE.DEPT_NO, D.DEPT_NAME, AVG(S.SALARY) 평균급여
FROM DEPARTMENTS D, DEPT_EMP DE, SALARIES S
WHERE D.DEPT_NO = DE.DEPT_NO AND DE.EMP_NO = S.EMP_NO AND
	  S.TO_DATE = '9999-01-01'
GROUP BY DE.DEPT_NO, D.DEPT_NAME;

-- 8. 직급별 직원의 평균 급여
SELECT T.TITLE, AVG(S.SALARY) 평균급여
FROM TITLES T, SALARIES S
WHERE T.EMP_NO = S.EMP_NO AND
	  T.TO_DATE = '9999-01-01' AND S.TO_DATE = '9999-01-01'
GROUP BY T.TITLE;

-- 9. 성별 평균 급여 조회
SELECT E.GENDER, AVG(S.SALARY) 평균급여
FROM EMPLOYEES E, SALARIES S
WHERE E.EMP_NO = S.EMP_NO AND
	  S.TO_DATE = '9999-01-01'
GROUP BY E.GENDER;

-- 10. 부서 이동 횟수가 2 이상인 직원 조회