-- 작업 데이터베이스 변경
USE MADANG;

-- 테이블 만들기 : NEWBOOK
-- 속성 : BOOKID(숫자형), BOOKNAME(문자형), PUBLISHER(문자형), PRICE(숫자형) 
CREATE TABLE NEWBOOK
(
	BOOKID INTEGER,
    BOOKNAME VARCHAR(100),
    PUBLISHER VARCHAR(50),
    PRICE INTEGER
);

-- 테이블 삭제 (테이블에 저장된 데이터도 같이 삭제)
DROP TABLE NEWBOOK;

-- 테이블 만들기 : NEWBOOK, 기본키 지정
CREATE TABLE NEWBOOK1
(
	BOOKID INTEGER PRIMARY KEY,
    BOOKNAME VARCHAR(100),
    PUBLISHER VARCHAR(50),
    PRICE INTEGER
);

CREATE TABLE NEWBOOK2
(
	BOOKID INTEGER,
    BOOKNAME VARCHAR(100),
    PUBLISHER VARCHAR(50),
    PRICE INTEGER,
    CONSTRAINT PK_NEWBOOK2 PRIMARY KEY (BOOKID)
);

CREATE TABLE NEWBOOK3
(
	BOOKID INTEGER,
    BOOKNAME VARCHAR(100),
    PUBLISHER VARCHAR(50),
    PRICE INTEGER,
    CONSTRAINT PK_NEWBOOK3 PRIMARY KEY (BOOKNAME, PUBLISHER)
);
DROP TABLE NEWBOOK1;
DROP TABLE NEWBOOK2;
DROP TABLE NEWBOOK3;

-- 테이블 만들기 : NOT NULL 제약, DEFAULT 제약, CHECK 제약, AUTO_INCREMENT
CREATE TABLE NEWBOOK
(
	BOOKID INTEGER NOT NULL AUTO_INCREMENT, -- AUTO_INCREMENT : 자동 증가 설정
    BOOKNAME VARCHAR(100) NOT NULL,
    PUBLISHER VARCHAR(50) NOT NULL,
    PRICE INTEGER NULL CHECK(PRICE >= 0), -- PRICE의 값은 0이상만 가능
    PUBDATE DATE DEFAULT(NOW()), -- 값이 지정되지 않은 경우 현재 시간 사용
    CONSTRAINT PK_NEWBOOK PRIMARY KEY (BOOKID)
);
DROP TABLE NEWBOOK;

-- 테이블 만들기 : NEWCUSTOMER
-- 속성 : CUSTID(숫자형), NAME(문자형), ADDRESS(문자형), PHONE(문자형)
CREATE TABLE NEWCUSTOMER
(
	CUSTID INT AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100) NULL,
    PHONE VARCHAR(15) NOT NULL,
    REGDATE DATE DEFAULT(NOW()),
    CONSTRAINT PK_NEWCUSTOMER PRIMARY KEY (CUSTID)
);
DROP TABLE NEWCUSTOMER;

-- 테이블 만들기 : NEWORDERS
-- 속성 : ORDERID(숫자형), CUSTID(숫자형), 
--       BOOKID(숫자형), SALEPRICE(숫자형), ORDERDATE(날짜형)
CREATE TABLE NEWORDERS
(
	ORDERID INT AUTO_INCREMENT,
    CUSTID INT NOT NULL,
    BOOKID INT NOT NULL,
    SALEPRICE INT NULL CHECK(SALEPRICE >= 0),
    ORDERDATE DATE DEFAULT(NOW()),
    CONSTRAINT PK_NEWORDERS PRIMARY KEY (ORDERID),
    CONSTRAINT FK_NEWBOOK_NEWORDERS FOREIGN KEY (BOOKID) REFERENCES NEWBOOK(BOOKID),
    CONSTRAINT FK_NEWCUSTOMER_NEWORDERS FOREIGN KEY (CUSTID) REFERENCES NEWCUSTOMER(CUSTID)
);
DROP TABLE NEWORDERS;

-- 테이블 제거
DROP TABLE NEWCUSTOMER; -- 자식 테이블이 있으면 삭제 불가

-- 테이블 수정
-- NEWBOOK 테이블에 ISBN 컬럼 추가
ALTER TABLE NEWBOOK
ADD ISBN VARCHAR(13) NOT NULL UNIQUE;

-- NEWBOOK 테이블의 ISBN 컬럼을 INT로 변경
ALTER TABLE NEWBOOK
MODIFY ISBN INT;

-- NEWBOOK 테이블의 ISBN 컬럼 삭제
ALTER TABLE NEWBOOK
DROP COLUMN ISBN;

-- 테스트용 테이블 만들기
CREATE TABLE TEST_TBL
(
	TEST_NO INT,
    TEST_DESC VARCHAR(1000)
);

-- TEST_TBL 테이블의 TEST_NO 컬럼에 NOT NULL 추가
ALTER TABLE TEST_TBL
MODIFY TEST_NO INT NOT NULL;

-- TEST_TBL 테이블의 TEST_NO 컬럼을 PRIMARY KEY로 변경
ALTER TABLE TEST_TBL
ADD CONSTRAINT PK_TEST_TBL PRIMARY KEY (TEST_NO);






